package exception;

import java.util.Scanner;

class Test
{
	public void display(int k)
	{
		try {
			
			
			int i = 10/k;
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		System.out.println("mehod complted");
		
	}
}

public class FinallyDemo {
	public static void main(String[] args) {
		
		
		
	
		
	}
}
